apiVersion: v1
kind: Pod
metadata:
  name: esde-api
  labels:
    app: my-test-app  # This is necessary to match the label with the Deployment
spec:
  containers:
  - name: esde-api
    image: esde_api:latest
    imagePullPolicy: Never
    resources:
      limits:
        memory: "200Mi"