apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment-esde
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-test-app
  template:
    metadata:
      labels:
        app: my-test-app
    spec:
      containers:
        - name: esde-api
          image: esde_api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 30
          resources:
            requests:
              cpu: "100m"
